/*
 * Copyright (c) 2002-2020, City of Paris
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  1. Redistributions of source code must retain the above copyright notice
 *     and the following disclaimer.
 *
 *  2. Redistributions in binary form must reproduce the above copyright notice
 *     and the following disclaimer in the documentation and/or other materials
 *     provided with the distribution.
 *
 *  3. Neither the name of 'Mairie de Paris' nor 'Lutece' nor the names of its
 *     contributors may be used to endorse or promote products derived from
 *     this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * License 1.0
 */
package fr.paris.lutece.plugins.jasper.service;

import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

/**
 * Interface to generate a Jasper report
 *
 */
public interface ILinkJasperReport extends Cloneable
{
    /**
     * Gives the link used to generate the report
     * 
     * @param strReportCode
     *            the report id
     * @return the link
     */
    String getLink( String strReportCode );

    /**
     * Gives the data generated by Jasper
     * 
     * @param strReportCode
     *            the report id
     * @param request
     *            the request
     * @return the data
     */
    byte [ ] getBuffer( String strReportCode, HttpServletRequest request );

    /**
     * Gives the data generated by Jasper
     * 
     * @param strReportCode
     *            the report id
     * @param dataSource
     *            the datasource
     * @param parameters
     *            parameters to set
     * @param request
     *            the httprequest
     * @return the data
     */
    byte [ ] getBuffer( String strReportCode, JRBeanCollectionDataSource dataSource, Map<String, Object> parameters, HttpServletRequest request );

    /**
     * Gives the data generated by Jasper
     * 
     * @param strReportCode
     *            the report id
     * @param dataSource
     *            the datasource
     * @param parameters
     *            parameters to set
     * @param request
     *            the httprequest
     * @return the data
     */
    byte [ ] getBuffer( String strReportCode, JRDataSource dataSource, Map<String, Object> parameters, HttpServletRequest request );

    /**
     * Gives the data generated by Jasper
     * 
     * @param report
     *            the report object
     * @param dataSource
     *            the datasource
     * @param parameters
     *            parameters to set
     * @param request
     *            the httprequest
     * @return the data
     */
    byte [ ] getBuffer( fr.paris.lutece.plugins.jasper.business.JasperReport report, JRBeanCollectionDataSource dataSource, Map<String, Object> parameters,
            HttpServletRequest request );

    /**
     * Gives the data generated by Jasper
     * 
     * @param report
     *            the report object
     * @param dataSource
     *            the datasource
     * @param parameters
     *            parameters to set
     * @param request
     *            the httprequest
     * @return the data
     */
    byte [ ] getBuffer( fr.paris.lutece.plugins.jasper.business.JasperReport report, JRDataSource dataSource, Map<String, Object> parameters,
            HttpServletRequest request );

    /**
     * Gives the name of the file generated by Jasper
     * 
     * @param strReportCode
     *            the report code
     * @return the file name
     */
    String getFileName( String strReportCode );

    /**
     * Gives the type of the file generated by Jasper
     * 
     * @return the file type
     */
    String getFileType( );
}
